export const ACTIONS = {
  GET_NEXT_MONTH: "GET_NEXT_MONTH",
  GET_PREVIOUS_MONTH: "GET_PREVIOUS_MONTH",
  SELECT_DAY: "SELECT_DAY",
  ADD_DEAL: "ADD_DEAL",
  UPDATE_DEAL: "UPDATE_DEAL",
  OPEN_FORM_ADD_DEAL: "OPEN_FORM_ADD_DEAL",
  CLOSE_FORM_ADD_DEAL: "CLOSE_FORM_ADD_DEAL",
  GET_USER_DEALS: "GET_USER_DEALS",
  ADD_ARTICLES: "GET_ARTICLES",
  OPEN_ACCES: "OPEN_ACCES",
  CLOSE_ACCES: "CLOSE_ACCES",
};
